# Generated by Django 5.0.3 on 2024-04-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_leg_uniqueorderid_alter_signinuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default='21E21264642297261038541', max_length=100),
        ),
    ]
