# Generated by Django 5.0.3 on 2024-04-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_signinuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='orderid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default='B838388456433821522065377', max_length=100),
        ),
    ]
