# Generated by Django 5.0.3 on 2024-04-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_leg_orderid_alter_signinuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='orderstatus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default='80F806437774621875788', max_length=100),
        ),
    ]
