# Generated by Django 5.0.4 on 2024-04-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_leg_orderstatus_leg_reason_alter_signinuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='ltp_status',
            field=models.CharField(blank=True, default='matching..', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='mkt_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default='5785785465458416209', max_length=100),
        ),
    ]
