# Generated by Django 5.0.4 on 2024-04-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_leg_ltp_status_leg_mkt_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='mkt_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default='78B782432486647497473585565', max_length=100),
        ),
    ]
