# Generated by Django 5.0.4 on 2024-04-12 13:08

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_signinuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='stoplossstatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='triggerstatus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default=app.models.generate_uuid_pattern, max_length=100),
        ),
    ]
