# Generated by Django 5.0.4 on 2024-04-15 05:34

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_leg_stoplossstatus_leg_triggerstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_name',
            name='symboltoken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leg',
            name='nse_symboltoken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default=app.models.generate_uuid_pattern, max_length=100),
        ),
    ]
