# Generated by Django 5.0.4 on 2024-04-15 08:22

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_company_name_symboltoken_leg_nse_symboltoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='placed_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default=app.models.generate_uuid_pattern, max_length=100),
        ),
    ]
