# Generated by Django 5.0.4 on 2024-04-16 11:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_leg_exitwhereitis_alter_signinuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='leg_id',
            field=models.CharField(default=app.models.leg_uuid, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default=app.models.generate_uuid_pattern, max_length=100),
        ),
    ]
