# Generated by Django 5.0.4 on 2024-04-18 12:44

import app.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_leg_leg_id_alter_leg_ltp_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default=app.models.generate_uuid_pattern, max_length=100),
        ),
        migrations.CreateModel(
            name='pl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plid', models.CharField(default=app.models.pl_uuid, max_length=100, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('trading_symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('profit_loss', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.signinuser')),
            ],
        ),
    ]
