# Generated by Django 5.0.4 on 2024-04-20 06:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_signinuser_user_id_pl'),
    ]

    operations = [
        migrations.AddField(
            model_name='leg',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default=app.models.generate_uuid_pattern, max_length=100),
        ),
    ]
