# Generated by Django 5.0.4 on 2024-04-24 13:08

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_leg_cancel_alter_signinuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default=app.models.generate_uuid_pattern, max_length=100),
        ),
        migrations.CreateModel(
            name='themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default=app.models.pl_uuid, max_length=100, unique=True)),
                ('navbar', models.CharField(default=app.models.pl_uuid, max_length=100, unique=True)),
                ('body', models.CharField(default=app.models.pl_uuid, max_length=100, unique=True)),
                ('legs', models.CharField(default=app.models.pl_uuid, max_length=100, unique=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.signinuser')),
            ],
        ),
    ]
